<?php
return array (
  145 => 
  array (
    'id' => '145',
    'catid' => '16',
    'typeid' => '0',
    'title' => '广东省委常委、宣传部长慎海雄走访中新社广东分社 ',
    'style' => '',
    'thumb' => 'http://i2.chinanews.com/simg/2017/170207//63805950.jpg',
    'keywords' => '',
    'description' => '广东省委常委、宣传部部长慎海雄观看中新社制作的《侨乡广东》专版。　陈骥旻 摄　　中新网广州2月7日电 (记者 唐贵江)广东省委常委、宣   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms20170206/index.php?m=content&c=index&a=show&catid=16&id=145',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487782698',
    'updatetime' => '1487782751',
    'hitsid' => 'c-1-145',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  73 => 
  array (
    'id' => '73',
    'catid' => '16',
    'typeid' => '0',
    'title' => '广东纪委监察厅举行2016年度领导班子民主生活会',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '　　中新网广州1月20日电(索有为 粤纪宣)中共广东省纪委、广东省监察厅20日举行2016年度领导班子民主生活会，中共广东省委常委、省纪委书   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms20170206/index.php?m=content&c=index&a=show&catid=16&id=73',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487782592',
    'updatetime' => '1487782746',
    'hitsid' => 'c-1-73',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  75 => 
  array (
    'id' => '75',
    'catid' => '16',
    'typeid' => '0',
    'title' => '肇庆警方开展“与法同行，共创文明”普法宣传',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '　　中新网肇庆1月20日电 (索有为 莫文辉)广东省肇庆市公安局20日在端州区出头社区开展预防电信诈骗普法宣传。　　当天，出头村公园拉起   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms20170206/index.php?m=content&c=index&a=show&catid=16&id=75',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487782593',
    'updatetime' => '1487782746',
    'hitsid' => 'c-1-75',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  76 => 
  array (
    'id' => '76',
    'catid' => '16',
    'typeid' => '0',
    'title' => '广东检方推动全面从严治检进一步走向“严紧硬” ',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '　　中新网广州1月20日电(索有为 韦磊)广东省检察院20日举行党组扩大会，传达学习十八届中央纪委七次全会、广东省纪委十一届六次全会精神   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms20170206/index.php?m=content&c=index&a=show&catid=16&id=76',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487782614',
    'updatetime' => '1487782746',
    'hitsid' => 'c-1-76',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  77 => 
  array (
    'id' => '77',
    'catid' => '16',
    'typeid' => '0',
    'title' => '韶关市委书记：像保护眼睛一样保护生态环境',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '　　中新网广州1月20日电 (记者 索有为)广东省十二届人大五次会议正在广州举行，广东省人大代表、韶关市委书记江凌在韶关代表团开放团组   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms20170206/index.php?m=content&c=index&a=show&catid=16&id=77',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487782614',
    'updatetime' => '1487782746',
    'hitsid' => 'c-1-77',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  78 => 
  array (
    'id' => '78',
    'catid' => '16',
    'typeid' => '0',
    'title' => '茂名市警方举行“飓风2016”专项行动成果展',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '　　中新网茂名1月20日电 (梁盛 梁晶晶 茂公宣)20日，茂名市警方&ldquo;飓风2016&rdquo;专项行动成果展拉开帷幕，此次成果展时间从1月20日持续至2   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms20170206/index.php?m=content&c=index&a=show&catid=16&id=78',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487782615',
    'updatetime' => '1487782746',
    'hitsid' => 'c-1-78',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  79 => 
  array (
    'id' => '79',
    'catid' => '16',
    'typeid' => '0',
    'title' => '政协委员建议加大资金投入 打造更多粤港澳文化名片',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '　　中新网珠海1月21日电 (记者 邓媛文)在近日召开的珠海市政协会议上，致公党珠海市委会支部副主委朱希向珠海市政协上交提案，建议加大   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms20170206/index.php?m=content&c=index&a=show&catid=16&id=79',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487782615',
    'updatetime' => '1487782746',
    'hitsid' => 'c-1-79',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  80 => 
  array (
    'id' => '80',
    'catid' => '16',
    'typeid' => '0',
    'title' => '广东副省长李春生赴佛山慰问因公负伤民警林伟光',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '　　中新网广州1月22日电(索有为 李志雄)广东省副省长、省公安厅党委书记、厅长李春生22日赴佛山看望慰问在执行抓捕任务重中负伤的佛山市   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms20170206/index.php?m=content&c=index&a=show&catid=16&id=80',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487782618',
    'updatetime' => '1487782746',
    'hitsid' => 'c-1-80',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>