<?php
return array (
  70 => 
  array (
    'id' => '70',
    'catid' => '11',
    'typeid' => '0',
    'title' => '河北回应法院参加招商引资培训会：仅列席听会|法院|招商',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '　　原标题：河北卢龙政府回应&ldquo;法院参加招商引资培训会&rdquo;：仅列席听会 没有招商任务　　法制晚报讯（记者 杜雯雯）近日，有网友反映，河   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms20170206/index.php?m=content&c=index&a=show&catid=11&id=70',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487698602',
    'updatetime' => '1487698602',
  ),
  71 => 
  array (
    'id' => '71',
    'catid' => '11',
    'typeid' => '0',
    'title' => '丽江被打女子容貌难恢复 多位施暴者无业难赔偿|丽江|旅游',
    'style' => '',
    'thumb' => 'http://p.ivideo.sina.com.cn/video/250/991/967/250991967.jpg',
    'keywords' => '',
    'description' => '                        视频加载中，请稍候                                    ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms20170206/index.php?m=content&c=index&a=show&catid=11&id=71',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487698602',
    'updatetime' => '1487698602',
  ),
  68 => 
  array (
    'id' => '68',
    'catid' => '11',
    'typeid' => '0',
    'title' => '陕西官员被曝当着二奶面嫖娼 纪委介入调查|嫖娼|官员|榆林',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '　　新京报快讯（记者王煜）一组涉及官员的不雅照，近日引发舆论关注。网友消息称，照片中所涉官员系陕西榆林市人社局一名徐姓科长。今日（   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms20170206/index.php?m=content&c=index&a=show&catid=11&id=68',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487698601',
    'updatetime' => '1487698601',
  ),
  69 => 
  array (
    'id' => '69',
    'catid' => '11',
    'typeid' => '0',
    'title' => '北京国Ⅰ国Ⅱ车15日起五环内禁行|五环|禁行|北京',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '　　原标题：国Ⅰ国Ⅱ车周三起五环内禁行　　法制晚报讯（记者 耿学清 编辑 田野） 本周三（2月15日）起，北京将对全市及外埠的国Ⅰ国   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms20170206/index.php?m=content&c=index&a=show&catid=11&id=69',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487698601',
    'updatetime' => '1487698601',
  ),
  66 => 
  array (
    'id' => '66',
    'catid' => '11',
    'typeid' => '0',
    'title' => '陕西榆林官员被指当着二奶面嫖娼 纪委介入调查|嫖娼|二',
    'style' => '',
    'thumb' => 'http://n.sinaimg.cn/news/crawl/20170213/aBx6-fyamkqa5881028.jpg',
    'keywords' => '',
    'description' => '　　原标题：网曝陕西榆林一官员当着二奶面嫖娼 纪委介入调查 图中（右一）为被举报的徐彦江　　这两天，微博被两张床照刷屏。原来是，&ldquo;   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms20170206/index.php?m=content&c=index&a=show&catid=11&id=66',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487698600',
    'updatetime' => '1487698600',
  ),
  67 => 
  array (
    'id' => '67',
    'catid' => '11',
    'typeid' => '0',
    'title' => '德媒:对中国独生子女预测都错了 更具有独立性|独生子女|',
    'style' => '',
    'thumb' => 'http://n.sinaimg.cn/translate/20170213/liXI-fyamkra7184373.jpg',
    'keywords' => '',
    'description' => '　　原标题：德媒：当年对中国&ldquo;小皇帝&rdquo;的预测都错了　　德国《莱茵邮报》2月11日发表了一篇题为《&ldquo;小皇帝&rdquo;正在长大》的文章。文章指出   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms20170206/index.php?m=content&c=index&a=show&catid=11&id=67',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487698600',
    'updatetime' => '1487698600',
  ),
);
?>