<?php
return array (
  2 => 
  array (
    'id' => '2',
    'catid' => '11',
    'typeid' => '0',
    'title' => 'aa',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    'posids' => '0',
    'url' => 'http://localhost/phpcms20170206/index.php?m=content&c=index&a=show&catid=11&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487695033',
    'updatetime' => '1487698803',
    'hitsid' => 'c-1-2',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  57 => 
  array (
    'id' => '57',
    'catid' => '11',
    'typeid' => '0',
    'title' => '谣言再度缠上中国：派500人插手印尼选举省长|选举|印尼|',
    'style' => '',
    'thumb' => 'http://n.sinaimg.cn/translate/20170213/xrYf-fyamvns5028642.jpg',
    'keywords' => '',
    'description' => '　　原标题：中国派500人插手？印尼选举省长谣言缠上中国资料图：钟万学　　[环球网军事2月13日报道 环球时报驻印尼特约记者 游弦鹤]印尼   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms20170206/index.php?m=content&c=index&a=show&catid=11&id=57',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487698592',
    'updatetime' => '1487698888',
    'hitsid' => 'c-1-57',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  71 => 
  array (
    'id' => '71',
    'catid' => '11',
    'typeid' => '0',
    'title' => '丽江被打女子容貌难恢复 多位施暴者无业难赔偿|丽江|旅游',
    'style' => '',
    'thumb' => 'http://p.ivideo.sina.com.cn/video/250/991/967/250991967.jpg',
    'keywords' => '',
    'description' => '                        视频加载中，请稍候                                    ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms20170206/index.php?m=content&c=index&a=show&catid=11&id=71',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487698602',
    'updatetime' => '1487776927',
    'hitsid' => 'c-1-71',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '11',
    'typeid' => '0',
    'title' => '海南官员因网站不更新被立案审查 成为全国首例|网站|海',
    'style' => '',
    'thumb' => 'http://n.sinaimg.cn/news/transform/20170212/Vs5L-fyamvns4932799.jpg',
    'keywords' => '',
    'description' => '　　原标题：问责丨海南一局长被立案审查 因为这个成为全国首例！　　近日，国务院办公厅公布了2016年第四次全国政府网站抽查情况，至此，   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms20170206/index.php?m=content&c=index&a=show&catid=11&id=5',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487698572',
    'updatetime' => '1487698732',
    'hitsid' => 'c-1-5',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  7 => 
  array (
    'id' => '7',
    'catid' => '11',
    'typeid' => '0',
    'title' => '专家:中华穿山甲比大熊猫珍贵 很多人吃为炫耀|穿山甲|大',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '　　原标题：从随处可见到极度濒危 几十年来，穿山甲经历了什么　　浙江在线2月15日讯（浙江在线记者 王曦煜） 最近，穿山甲突然成了热   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms20170206/index.php?m=content&c=index&a=show&catid=11&id=7',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487698564',
    'updatetime' => '1487698765',
    'hitsid' => 'c-1-7',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  8 => 
  array (
    'id' => '8',
    'catid' => '11',
    'typeid' => '0',
    'title' => '湄公河事件船长:执法船险遭糯康集团火箭弹袭击|糯康|湄公',
    'style' => '',
    'thumb' => 'http://n.sinaimg.cn/news/crawl/20170220/fgQR-fyarrcf4871053.jpg',
    'keywords' => '',
    'description' => '　　原标题：湄公河事件老船长：执法船险遭糯康集团火箭弹袭击　　巡逻艇编队航行&ldquo;湄公河第一哨&rdquo;官兵在界碑前宣誓官兵在船艇甲板列队清晨   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms20170206/index.php?m=content&c=index&a=show&catid=11&id=8',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487698565',
    'updatetime' => '1487698765',
    'hitsid' => 'c-1-8',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  9 => 
  array (
    'id' => '9',
    'catid' => '11',
    'typeid' => '0',
    'title' => '老兵王琪返乡 老排长带战友聚会画册来接机(图)|王琪|老',
    'style' => '',
    'thumb' => 'http://n.sinaimg.cn/news/transform/20170212/zwpv-fyamkqa5699848.jpg',
    'keywords' => '',
    'description' => '　　原标题：老排长带战友聚会画册赶来　　昨日中午，华商报记者接到一位老先生的电话，他说自己叫王祖国，今年80岁，是王琪当年所在部队的   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms20170206/index.php?m=content&c=index&a=show&catid=11&id=9',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487698565',
    'updatetime' => '1487698765',
    'hitsid' => 'c-1-9',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  10 => 
  array (
    'id' => '10',
    'catid' => '11',
    'typeid' => '0',
    'title' => '老兵王琪回到老家咸阳 连吃7碗手擀浇汤面(图)|王琪|老兵',
    'style' => '',
    'thumb' => 'http://n.sinaimg.cn/translate/20170212/rzLn-fyamkqa5701007.jpg',
    'keywords' => '',
    'description' => '                        视频加载中，请稍候                                    ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms20170206/index.php?m=content&c=index&a=show&catid=11&id=10',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487698566',
    'updatetime' => '1487698765',
    'hitsid' => 'c-1-10',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>