<?php
return array (
  10 => 
  array (
    'catid' => '10',
    'siteid' => '2',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '10',
    'catname' => 'cyb一级',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'cyb_a',
    'url' => 'http://localhost/phpcms20170206/index.php?m=content&c=index&a=lists&catid=10',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"cyb","category_template":"category","list_template":"list","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '10',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'cybyiji',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
);
?>